version: "2.1"
volumes:
  xserver:
services:
  balena-control:
    build: .
    restart: always
    privileged: true
    network_mode: host
    devices:
      - /dev/dri
    group_add:
      - video
    ports:
      - 3009:3009
      - 3005:3005
      - 80:80
      - "161:161/udp"
      - "162:162/udp"
    volumes:
      - "xserver:/tmp/.X11-unix"
    labels:
      io.resin.features.dbus: "1"
      io.resin.features.kernel-modules: "1"
      io.resin.features.firmware: "1"
      io.balena.features.supervisor-api: "1"
